In [2]:
import gym
import torch
import torch.nn as nn
import numpy as np

In [3]:
env = gym.make("CartPole-v0")

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [4]:
obs = env.reset()

In [5]:
obs

array([-0.02989374,  0.03143096, -0.03042474,  0.04732943])

In [6]:
class Net(nn.Module):
    def __init__(self, obs_size, hidden_size, n_actions):
        super(Net, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(obs_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, n_actions)
        )

    def forward(self, x):
        return self.net(x)

In [7]:
obs_size = env.observation_space.shape[0]
n_actions = env.action_space.n
HIDDEN_SIZE = 5
net = Net(obs_size, HIDDEN_SIZE, n_actions)

In [8]:
obs = env.reset()
obs_v = torch.FloatTensor([obs])
sm = nn.Softmax(dim=1)
act_probs_v = sm(net(obs_v))

In [9]:
act_probs_v

tensor([[0.4930, 0.5070]], grad_fn=<SoftmaxBackward>)

In [10]:
act_probs = act_probs_v.data.numpy()[0]
print(act_probs)

[0.4929854  0.50701463]


In [15]:
action = np.random.choice(len(act_probs), p=act_probs)
print(action)

1


In [17]:
next_obs, reward, is_done, _ = env.step(action)
print(reward, is_done)

1.0 False


In [12]:
temp = t_tensor.detach().numpy()

In [13]:
temp

array([[-0.3942389 , -0.36617857]], dtype=float32)

In [14]:
import nzl_util as nzl
temp = temp.flatten()
sm_test = nzl.softmax(temp)
print(sm_test)

[0.53485614 0.46514386]
[0.49298537 0.50701463]
