In [61]:
import numpy as np

In [62]:
T = np.array([[[0.5,0.5,0,0],[0,1,0,0],[0.5,0.5,0,0],[0,1,0,0]], \
			  [[1,0,0,0],[0.5,0,0,0.5],[0.5,0,0.5,0],[0,0,0.5,0.5]]])

In [63]:
R = np.array([[0,0,10,10], \
			  [0,0,10,10]])

In [70]:
for n in range(3):
    V_old = np.ones((4,1))
    V_new = np.ones((4,1))
    V_new = []
    for a in range(2):
        temp = 1 * np.matmul(T[a, :, :], V_old)
        V_new.append(R[a, :] + temp)
        V_new.append(R[a, :].reshape(temp.shape) + temp)

    V_new = np.stack(V_new, axis=-1)
    V_new = np.amax(V_new, axis=-1)
    print(n, V_new)

0 [[ 1.  1. 11. 11.]
 [ 1.  1. 11. 11.]
 [ 1.  1. 11. 11.]
 [ 1.  1. 11. 11.]]
1 [[ 1.  1. 11. 11.]
 [ 1.  1. 11. 11.]
 [ 1.  1. 11. 11.]
 [ 1.  1. 11. 11.]]
2 [[ 1.  1. 11. 11.]
 [ 1.  1. 11. 11.]
 [ 1.  1. 11. 11.]
 [ 1.  1. 11. 11.]]


In [67]:
V_new

array([[ 1.],
       [ 1.],
       [11.],
       [11.]])

In [54]:
 R[a, :].reshape(temp.shape) + temp

array([[ 1.],
       [ 1.],
       [11.],
       [11.]])

In [17]:
V_new = np.amax(V_new, axis=-1)

In [18]:
V_new

array([[ 1.,  1., 11., 11.],
       [ 1.,  1., 11., 11.],
       [ 1.,  1., 11., 11.],
       [ 1.,  1., 11., 11.]])

In [10]:
R[0, :] + np.matmul(T[0, :, :], V_old)

array([[ 1.,  1., 11., 11.],
       [ 1.,  1., 11., 11.],
       [ 1.,  1., 11., 11.],
       [ 1.,  1., 11., 11.]])