In [1]:
import numpy as np
from MDP_alg1 import MDP

In [2]:
T = np.array([[[0.5,0.5,0,0], [0,1,0,0],     [0.5,0.5,0,0], [0,1,0,0]],
	          [[1,0,0,0],     [0.5,0,0,0.5], [0.5,0,0.5,0], [0,0,0.5,0.5]]])
R = np.array([[0,0,10,10], [0,0,10,10]])
discount = 0.9        
mdp = MDP(T, R, discount)

In [3]:
cumProb = np.cumsum(mdp.T[1,1,:])
print(cumProb)

[0.5 0.5 0.5 1. ]


In [17]:
nextState = np.where(cumProb >= np.random.rand(1))[0][0]
print(nextState)

3


In [7]:
t = np.random.rand(1)
print(t)

[0.43223884]


In [8]:
cumProb >= t

array([ True,  True,  True,  True])

In [16]:
t1 = np.where(cumProb >= t)
print(t1, t1[0], t1[0][0])

(array([0, 1, 2, 3], dtype=int64),) [0 1 2 3] 0


In [13]:
t1

(array([0, 1, 2, 3], dtype=int64),)

In [18]:
nextState = np.where(cumProb >= np.random.rand(1))[0][0]
print(nextState)

0


In [31]:
x = np.ma.array(np.arange(12).reshape(3, 4), mask=[[0, 1, 0, 0],[1, 0, 1, 0],[0, 1, 0, 0]])
y = np.arange(12).reshape(3, 4)

In [32]:
print(x)

[[0 -- 2 3]
 [-- 5 -- 7]
 [8 -- 10 11]]


In [33]:
np.ma.where(x > 5)

(array([1, 2, 2, 2], dtype=int64), array([3, 0, 2, 3], dtype=int64))

In [34]:
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
np.ma.where(y > 5)

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [44]:
np.random.rand(1)

array([0.78645617])

In [42]:
np.random.randint(2)

0