In [1]:
import numpy as np

In [ ]:
# print("Taking action: {}".format(["Stick", "Hit"][action]))
# action = np.random.choice(np.arange(len(probs)), p=probs)

# # OPTION 2: construct a stochastic policy that puts equal probability on maximizing actions
# best_a = np.argwhere(q==np.max(q)).flatten()
# policy[s] = np.sum([np.eye(env.nA)[i] for i in best_a], axis=0)/len(best_a)

In [11]:
q = np.array([1, 2, 3, 3, 2, 2])
best_a = np.argwhere(q==np.max(q)).flatten()
print(best_a)

[2 3]


In [12]:
policy = np.sum([np.eye(6)[i] for i in best_a], axis=0)/len(best_a)
print(policy)

[0.  0.  0.5 0.5 0.  0. ]


In [13]:
np.sum([np.eye(6)[i] for i in best_a], axis=0)

array([0., 0., 1., 1., 0., 0.])

In [14]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
a = np.eye(6)[2]
b = np.eye(6)[3]
print(a,b)

[0. 0. 1. 0. 0. 0.] [0. 0. 0. 1. 0. 0.]


In [17]:
a+b

array([0., 0., 1., 1., 0., 0.])