In [1]:
import torch
from torch.autograd import Variable

In [8]:
x_data = [1.0, 2.0, 3.0]
y_data = [2.0, 4.0, 6.0]

w = Variable(torch.Tensor([1.0]),  requires_grad=True)  # Any random value

# our model forward pass


def forward(x):
    return x * w

# Loss function


def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

# Before training
print("before training, x=",  4, "\t predict y=", forward(4).data[0])

# Training loop
alpha = 0.1
for epoch in range(5):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tx, y: ", x_val, y_val, "\t grad:", w.grad.data[0], "\t weight:", w.data)
        w.data = w.data - alpha * w.grad.data

        # Manually zero the gradients after updating weights
        w.grad.data.zero_()

    print("\t episode:", epoch, "loss:", l.data[0], "\n")

# After training
print("predict (after training)",  4, forward(4).data[0])
print('w', w.data)

before training, x= 4 	 predict y= tensor(4.)
	x, y:  1.0 2.0 	 grad: tensor(-2.) 	 weight: tensor([1.])
	x, y:  2.0 4.0 	 grad: tensor(-6.4000) 	 weight: tensor([1.2000])
	x, y:  3.0 6.0 	 grad: tensor(-2.8800) 	 weight: tensor([1.8400])
	 episode: 0 loss: tensor(0.2304) 

	x, y:  1.0 2.0 	 grad: tensor(0.2560) 	 weight: tensor([2.1280])
	x, y:  2.0 4.0 	 grad: tensor(0.8192) 	 weight: tensor([2.1024])
	x, y:  3.0 6.0 	 grad: tensor(0.3686) 	 weight: tensor([2.0205])
	 episode: 1 loss: tensor(0.0038) 

	x, y:  1.0 2.0 	 grad: tensor(-0.0328) 	 weight: tensor([1.9836])
	x, y:  2.0 4.0 	 grad: tensor(-0.1049) 	 weight: tensor([1.9869])
	x, y:  3.0 6.0 	 grad: tensor(-0.0472) 	 weight: tensor([1.9974])
	 episode: 2 loss: tensor(0.0001) 

	x, y:  1.0 2.0 	 grad: tensor(0.0042) 	 weight: tensor([2.0021])
	x, y:  2.0 4.0 	 grad: tensor(0.0134) 	 weight: tensor([2.0017])
	x, y:  3.0 6.0 	 grad: tensor(0.0060) 	 weight: tensor([2.0003])
	 episode: 3 loss: tensor(1.0123e-06) 

	x, y:  1.0 2.0 

In [18]:
def p2(x):
    return x*x

def p3(x):
    return x*x*x


In [48]:
x = Variable(torch.Tensor([2]), requires_grad=True)
a = p2(x)
b = p3(x)
c = b.detach().numpy()
y = a + torch.Tensor(c)
y = a + b
print(y)
print(x.grad)
print(c)

tensor([12.], grad_fn=<ThAddBackward>)
None
[8.]


In [49]:
y.backward()
print(x.grad)

tensor([16.])


In [47]:
x.grad.data.zero_()

tensor([0.])